version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo_server
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodb2020$
    volumes:
      - ~/.databases/mongodb:/data/db
    ports:
      - 27019:27017

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo_express
  #   restart: always
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=mongodb2020!
  #     - ME_CONFIG_MONGODB_URL=mongodb://root:mongodb2020!@mongo_server:27017/
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo

networks:
  default:
    name: mongodb_net



#Add permissions to .databases directory
#sudo chgrp -R 0 ~/.databases  
#sudo chmod -R g=u ~/.databases
