version: '3.1'

services:
  es01:
    container_name: es01
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - Des.enforce.bootstrap.checks=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - elastic-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.4.3
    ports:
      - 5601:5601
    depends_on:
      - es01
    environment:
      - ELASTICSEARCH_URL=http://es01:9200
    networks:
      - elastic-network

networks:
  elastic-network:
    driver: bridge

volumes:
  elasticsearch-data:
