version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: "mysqlserver"
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql2020$
    volumes:
      - ~/.databases/mysql/data:/var/lib/mysql

#Al iniciar sesion en phpmyadmin usar nombre del contenedor como servidor
  adminer:
    image: phpmyadmin
    container_name: mysql_phpadmin
    restart: always
    ports:
     - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql



#Add permissions to .databases directory
#sudo chgrp -R 0 ~/.databases  
#sudo chmod -R g=u ~/.databases

