version: '3.1'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: "mssqlserver"
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Mssql2020$
      - MSSQL_PID=Developer
    volumes:
      - ~/.databases/sqlserver/data:/var/opt/mssql/data
      - ~/.databases/sqlserver/log:/var/opt/mssql/log
      - ~/.databases/sqlserver/secrets:/var/opt/mssql/secrets



#
#docker compose -d up

#Add permissions to .databases directory
#sudo chgrp -R 0 ~/.databases  
#sudo chmod -R g=u ~/.databases
