services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    platform: linux/amd64
    container_name: "mssqlserver"
    restart: always
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Mssql2020$
      - MSSQL_PID=Developer
    user: "0:0"
    volumes:
      - /Users/emmanuelcaamal/.databases/sqlserver/data:/var/opt/mssql/data
      - /Users/emmanuelcaamal/.databases/sqlserver/log:/var/opt/mssql/log
      - /Users/emmanuelcaamal/.databases/sqlserver/secrets:/var/opt/mssql/secrets



#
#docker compose up -d

#Add permissions to .databases directory

# Cambiar el grupo del directorio a 'staff' (grupo predeterminado en macOS)
#sudo chgrp -R staff ~/.databases  

# Dar permisos de lectura y escritura al grupo
#sudo chmod -R 775 ~/.databases  
