version: "3.8"

services:
  postgres-server: 
    image: postgres:alpine
    container_name: "postgres_server"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pgsql2020$
      #- POSTGRES_DATABASE=testdb01
    volumes:
      - ~/.databases/postgres/data:/var/lib/postgresql/data

#Al iniciar sesion en pgadmin4 usar nombre del contenedor como servidor
  dbadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgsql2020!
    ports:
      - "5555:80"
    depends_on:
      - postgres-server


#Add permissions to .databases directory
#sudo chgrp -R 0 ~/.databases  
#sudo chmod -R g=u ~/.databases
