version: '3.1'

services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: local-azurite
    volumes:
      - c:/azurite:/data
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002